export default {
	PRODUCTS_FETCHED: 'PRODUCTS_FETCHED',
	PRODUCT_FETCHED:  'PRODUCT_FETCHED',
	ADDED_TO_CART: 'ADDED_TO_CART',
	CURRENT_USER_FETCHED: 'CURRENT_USER_FETCHED',
	CART_FETCHED: 'CART_FETCHED',
	ITEM_DELETED: 'ITEM_DELETED'
}