export default {
	PRODUCTS_FETCHED: 'PRODUCTS_FETCHED',
	PRODUCT_FETCHED:  'PRODUCT_FETCHED',
	ADDED_TO_CART: 'ADDED_TO_CART',
	CURRENT_USER_FETCHED: 'CURRENT_USER_FETCHED',
	CART_FETCHED: 'CART_FETCHED',
	ITEM_DELETED: 'ITEM_DELETED',
	PICTURES_UPLOADED: 'PICTURES_UPLOADED',
	PICTURE_DELETED: 'PICTURE_DELETED',
	NEW_CATEGORY_ADDED: 'NEW_CATEGORY_ADDED',
	NEW_SUBCATEGORY_ADDED: 'NEW_SUBCATEGORY_ADDED',
	CATEGORIES_FETCHED: 'CATEGORIES_FETCHED',
	SUB_CATEGORIES_FETCHED: 'SUB_CATEGORIES_FETCHED'
}